require("telescope").load_extension("fzf")
local builtin = require("telescope.builtin")
vim.keymap.set("n", "<leader>ff", builtin.fd, { desc = "Telescope find files" })
vim.keymap.set("n", "<leader>fa", builtin.builtin, { desc = "Telescope all" })
vim.keymap.set("n", "<leader>ft", function()
	builtin.colorscheme({ enable_preview = true })
end, { desc = "Telescope themes" })
vim.keymap.set("n", "<leader>fg", builtin.live_grep, { desc = "Telescope live grep" })
vim.keymap.set("n", "<leader>fb", builtin.buffers, { desc = "Telescope buffers" })
vim.keymap.set("n", "<leader>ld", builtin.diagnostics, { desc = "Lenguage diagnostics" })
vim.keymap.set("n", "<leader>ls", builtin.lsp_dynamic_workspace_symbols, { desc = "Lenguage simbols" })
vim.keymap.set("n", "gtd", builtin.lsp_type_definitions, { desc = "Lenguage type definition" })
vim.keymap.set("n", "gd", builtin.lsp_definitions, { desc = "Lenguage definition" })
vim.keymap.set("n", "gr", builtin.lsp_references, { desc = "Lenguage references" })
vim.keymap.set("n", "<leader>gc", builtin.git_commits, { desc = "Git commits" })
vim.keymap.set("n", "<leader>gb", builtin.git_branches, { desc = "Git branchs" })
vim.keymap.set("n", "<leader>gs", builtin.git_status, { desc = "Git status" })
